### ISSUE TITLE
You copied my software ESP32-Paxcounter and you removed the License

### ISSUE THREAD

**Issue by cyberman54** [dycodex/herd-counter#1]
Read and respect my license.
Otherwise i will flag your account at github.

**Comment by andriyadi** [comment]
Hi @cyberman54 
I'm truly sorry for that. It's ongoing coding, so the info on license, copyright, and link to original work are not yet published, as we need to have the code tried first. As you can see, the repo doesn't even have README now. Don't worry, I'm writing it now, adding the license and give the credit to you. 

Thanks for reminding.

**Comment by andriyadi** [comment]
@cyberman54 is [this](https://github.com/dycodex/herd-counter/blob/master/README.md) good enough? Please let me know your concern.

**Comment by cyberman54** [comment]
ok!
